### ISSUE TITLE
ForceItemRestoration deleting every item from my inventory after changing stages

### ISSUE THREAD

**Issue by multineer** [WondaMegapon/Refightilization#12]
Whenever i turn ForceItemRestoration "on" it removes everyone's items when we teleport to the next stage, this bug also works in singleplayer. I've tried turning it off and it worked just fine so im assuming the problem is in that setting!

**Comment by WondaMegapon** [comment]
Oh no! I'll look into that. Send me the logs and I'll see what I can do.

**Comment by multineer** [comment]
Sorry for the wait! Here: 
First one is with ForceItemRestoration Off and the second one is with ForceItemRestoration On. I grabbed items on the first stage, moved onto the next one and died there on both of the logs
[4af85dbb-772a-46c9-9c71-6f3d0aa6c78f.txt](https://github.com/WondaMegapon/Refightilization/files/7782477/4af85dbb-772a-46c9-9c71-6f3d0aa6c78f.txt)
[32e9b916-2f0f-4b82-9c36-778a86f954fc.txt](https://github.com/WondaMegapon/Refightilization/files/7782508/32e9b916-2f0f-4b82-9c36-778a86f954fc.txt)

**Comment by Bananapeelss** [comment]
This issue is still occurring, everyone in the lobbies items get removed after going to the next stage with ForceItemRestoration on.

**Comment by WondaMegapon** [comment]
ForceItemRestoration will be removed in 1.1.4, due to ItemPickupToggle existing, preventing monsters from taking items in the first place.
