### ISSUE TITLE
Submit translation

### ISSUE THREAD

**Issue by ClEeVEeRYT** [WondaMegapon/Refightilization#15]
Hi I translated your mod in french where should I submit it?

**Comment by WondaMegapon** [comment]
Either leaving the translations in a comment, DMing me on Discord the new translations, or setting up a pull request would work.

**Comment by ClEeVEeRYT** [comment]
okay thank you im going to shoot you a dm then

**Comment by WondaMegapon** [comment]
French added! It'll be available in the next patch, if you have your game language set to French.
