### ISSUE TITLE
Players never respawn in the planetarium (voidling boss area)

### ISSUE THREAD

**Issue by vommythegreat** [WondaMegapon/Refightilization#19]
This may or may not be intentional but i would just like to have the option to respawn there. I want to have it so a game over wont happen if everyone is a monster but if i have that on then the run is softlocked if everyone dies to voidling.

**Comment by WondaMegapon** [comment]
That's unintentional. I just assumed that respawning would work in the planetarium. Would you mind sending me your logs?

**Comment by vommythegreat** [comment]
[log.txt](https://github.com/WondaMegapon/Refightilization/files/8228882/log.txt)

**Comment by WondaMegapon** [comment]
Bug should be fixed in 1.1.3. Leaving the issue open just in case something breaks regarding Planetarium.
