### ISSUE TITLE
Death screen still there

### ISSUE THREAD

**Issue by person123421312** [WondaMegapon/Refightilization#25]
After I die and respawn the death screen is still there. I can't see anything during this time. Does anybody else have this issue?

**Comment by WondaMegapon** [comment]
What does your configuration file look like?

**Comment by person123421312** [comment]
How do you find that?

**Comment by WondaMegapon** [comment]
If you're using R2Modman, it should be in `PROFILE/BepInEx/config/com.Wonda.Refightilization.cfg`, otherwise it'll be somewhere where you put your mods. Having the logs from the sessions with the issue would also help, too.

**Comment by person123421312** [comment]
![image](https://user-images.githubusercontent.com/101996891/159186472-8863fdb5-81e2-4faa-861b-e1099ed04766.png)
![Capture](https://user-images.githubusercontent.com/101996891/159186496-ae693346-7d27-4480-993f-211ca093fff1.PNG)

**Comment by person123421312** [comment]
Also the logs from the games won't show in game.

**Comment by person123421312** [comment]
https://user-images.githubusercontent.com/101996891/159186898-f6ba1e9d-56c5-45dc-8fb5-66a80e00b648.mp4

**Comment by person123421312** [comment]
My config file looks fine.

**Comment by person123421312** [comment]
?

**Comment by person123421312** [comment]
Sir?

**Comment by WondaMegapon** [comment]
Ma'am, and you're playing on Singleplayer, meaning that the game will end once you die. There is an option in the configuration settings to disable having the game end, but it disables *all* game endings in the current patch of the mod.

**Comment by person123421312** [comment]
How do you disable the game end?

**Comment by person123421312** [comment]
Never mind. Thanks for the help!
