### ISSUE TITLE
Heart of the Void (AetheriumMod)

### ISSUE THREAD

**Issue by LordOfDespair** [WondaMegapon/Refightilization#3]
" I did change some settings, like to revive as a monster. "

In solo play :
When you die with "The Heart of the Void" it will trigger the event of becoming a monster and end the run, instead of simply reviving.

Items from:
https://github.com/KomradeSpectre/AetheriumMod

![image](https://user-images.githubusercontent.com/41344912/118273657-36a5ea00-b492-11eb-92d7-1bc3f30a0fb3.png)

**Comment by WondaMegapon** [comment]
This issue should now be resolved! The Heart of the Void would prevent a game over from occurring, so now the mod will respect it's prevention.
