### ISSUE TITLE
Artifact of Metamorphosis bug

### ISSUE THREAD

**Issue by notpeachie** [WondaMegapon/Refightilization#30]
Whenever I have metamorphosis enabled, I respawn as a character instead of a monster. This was not an issue until recently and i know that bc i always play with metamorphosis on lol.

**Comment by WondaMegapon** [comment]
I loooove Risk of Rain updates. I'll look into it in a few weeks, after finals. Hopefully I can iron out this and other issues by then.

**Comment by WondaMegapon** [comment]
This *should* be fixed in 1.2.0, but there's a config option to disable it since I know some folk love that behavior.
