### ISSUE TITLE
Clay Dunestrider Special locks

### ISSUE THREAD

**Issue by BronzeNoob** [WondaMegapon/Refightilization#31]
Whenever I transform in Clay Dunestrider and use the Special, it locks me in place and renders me unable to perform any kind of action. When there's nothing left to drain, it ends, but I'm stuck in the animation and am unable to move.

**Comment by WondaMegapon** [comment]
This behavior is out of the scope of the mod, but I can add the Dunestrider to the default blacklisted enemies.
