### ISSUE TITLE
Feature Suggestion: Config to disable player monster respawns after the teleporter is completed

### ISSUE THREAD

**Issue by gaforb** [WondaMegapon/Refightilization#4]
Semi-related, had a run end immediately because I respawned as a monster right as the other two players in the lobby teleported out. Didn't see anything in the log for it so I probably couldn't reproduce it.

**Comment by WondaMegapon** [comment]
The "NoRespawnsAfterTeleporter" config option has now been implemented. Thank you for the suggestion!
