### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by nullAdept** [WondaMegapon/Refightilization#40]
the mod doesnt work i think i have starstorm 2 and some other stuff it doesnt revive me

**Comment by WondaMegapon** [comment]
May you provide your logs from either your mod manager's debugging tab or from your BepInEx directory?

**Comment by nullAdept** [comment]
i am sorry i was drunk when i made this, it worked

**Comment by WondaMegapon** [comment]
No worries! Have a good day.
