### ISSUE TITLE
List of monster bodies, possible blacklist issues

### ISSUE THREAD

**Issue by Picothea** [WondaMegapon/Refightilization#5]
Hiya, I'm sorry if I've blatantly missed this somewhere, but could the mod be provided with a list of the monster "body" names for use in the blacklist?

I've used the ones I could find elsewhere, but the mod doesn't seem to ban them properly. Scavengers, for example, seem to be allowed for player respawns even if I've put them on the blacklist and toggled off the dedicated option for them.

Additionally, blacklisting some things seem to outright crash the game. I've only had this happen with greater wisps, so far. It would cause a crash whenever a player would seemingly be about to spawn as one, and this hasn't happened after un-blacklisting it.

Apologies if this issue writeup is lackluster in the end. I did want to report it, though, because I enjoy the mod a lot and hope to use it more.

**Comment by WondaMegapon** [comment]
No worries! Do you have any additional mods installed?

**Comment by Picothea** [comment]
> No worries! Do you have any additional mods installed?

No other mods, just the dependencies for this one. I've also been fiddling around with the blacklist, and for whatever reason, the crashing almost seems based on how many things are blacklisted rather than specific ones.

It's just... weird. But for whatever reason, un-blacklisting the normal beetle seemed to make it safe to blacklist the greater wisp.

**Comment by WondaMegapon** [comment]
Oh! That gives me a good image of what's happening!

It's probably getting hung up on there being no other monster to spawn as, since the entire pool is probably blacklisted with your config. Would you mind sharing what configuration is causing the crashes? 

I'll definitely look towards implementing a fix, since that gives me a pretty solid lead. Thank you!

**Comment by Picothea** [comment]
Oh, that might _not_ be it. This was on the 1st stages, with lemurians and scavengers (due to them spawning anyways) still available. I've changed the exact config since then, so I can't say for sure whether I also had golems and the rest on, but there were definitely more monsters to choose from.

Also, this may just be by chance, but it'd only happen when a player died who was already a monster. I only experienced it twice, though, before I changed the config to re-enable greater wisps.

**Comment by WondaMegapon** [comment]
Did you have any artifacts enabled?

**Comment by Picothea** [comment]
The artifact use varied, but in total I have used Chaos, Frailty, Command, and Sacrifice.

**Comment by Picothea** [comment]
I've been toying around with the config some more, and I think the game will crash if there's only 1 available monster to respawn as- but only once you've already respawned.

With my config, I was on a stage where the only available monster would be lemurians. Everyone who died could respawn as one without issues, but if they died AGAIN, then it would cause the game to crash when they were meant to spawn.

The active artifacts were Command, Sacrifice, and Frailty.

**Comment by WondaMegapon** [comment]
Alright, just pushed out a hotfix. Hopefully that should help?

**Comment by Picothea** [comment]
I installed the hotfix and tried again, but unfortunately it still crashed when I set the config back to only having 1 monster available. Still the same situation- players can respawn as one monster just fine, but if they die once more, it crashes.
I couldn't see everything on the console since it crashed so fast, but it was definitely remarking that a bunch of the bodies were disabled.
Is there any way it could simply accept respawning you as the monster body you had prior?

**Comment by WondaMegapon** [comment]
I'll add in a toggle option.

**Comment by WondaMegapon** [comment]
It's been added! The mod should be usable, now.

**Comment by Picothea** [comment]
The config option seems to have fixed the respawn crash without issue!

However, the problem where players who disconnect can cause softlocks still seems to be there. It seemed like you tried to fix that with the update as well, but it still happens.
Either way, as far as the respawn issue goes, this is all good now.

**Comment by WondaMegapon** [comment]
The disconnect issue should now be fixed!

**Comment by Picothea** [comment]
Ah yeah, it is! I tested it the other day and had no issues- sorry that I didn't comment sooner.

**Comment by WondaMegapon** [comment]
Radical! Then I'll close this issue. I hope you have a wonderful time!
