### ISSUE TITLE
Equipment error

### ISSUE THREAD

**Issue by Picothea** [WondaMegapon/Refightilization#6]
Occasionally, the affix/aspect equipment the game tries to give the player will be an error with no effect.
![billede](https://user-images.githubusercontent.com/79028970/126509762-101c034a-233a-43e9-b3ed-065c2ee67e92.png)

Aside from Refightilization and its dependencies, this is still a vanilla game, so only vanilla aspects would be available.

I tried to look through the console for anything odd during the respawning, but I couldn't find anything that seemed to be it. I did however occasionally see this blob of red text after a respawn:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Wonda.Refightilization.RefightRespawn (RoR2.CharacterMaster player, UnityEngine.Vector3 deathPos) (at <5c95413b001d45e293afa6d717ba7082>:IL_0436)
Wonda.Refightilization+<RespawnCheck>d__29.MoveNext () (at <5c95413b001d45e293afa6d717ba7082>:IL_01E1)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <2cc17dca390941eeb4d7b2ff1f84696a>:IL_0027)

**Comment by WondaMegapon** [comment]
The error aspect is the Coven of Gold. I'll see if I can add in edge cases for unimplemented aspects, though. 

As for the NRE, is there any further context for it?

**Comment by Picothea** [comment]
Not that I know of, no. Nothing else seemed wrong in-game.

**Comment by WondaMegapon** [comment]
I meant context to the console logs, like lines before and after the NRE. 😅

I can't identify exactly what caused the NRE when I don't have the LogInfo's to pinpoint where it occurred.

**Comment by Picothea** [comment]
Ah, sorry. I don't have the logs at hand anymore, but these would appear immediately after a respawn was completed, like I mentioned in the issue report.

**Comment by WondaMegapon** [comment]
These issues should be resolved, now! The coven of gold shouldn't appear, again, and there should be no more NRE.

**Comment by Picothea** [comment]
With a little testing, I no longer run into the Coven nor the NRE. Seems good!
